version: "3.8"

services:
  backend:
    build: ./fastapi-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./fastapi-backend/.env
    expose:
      - "8000"  # 내부에서만 접근 가능 (Nginx가 프록시 역할)
    networks:
      - app-network
    #ports:
    #  - "8000:8000"

  react:
    build: ./gpt-translator-extension
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    networks:
      - app-network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gpt_translator
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx:
    build:
      context: ./proxy-server
    container_name: nginx-proxy
    restart: always
    depends_on:
      - backend
    ports:
      - "443:443"  # HTTPS 지원
      - "80:80"
    volumes:
      - ./certs:/etc/nginx/certs  # SSL 인증서 마운트 (Dockerfile에서 복사하지 않음)
      - ./proxy-server/nginx.conf:/etc/nginx/nginx.conf  # nginx.conf 위치 변경 반영
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

